# Generated by Django 4.1.1 on 2022-10-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fkip', '0002_mahasiswa_staff_alter_dosen_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='photo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='photo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.CharField(max_length=50),
        ),
    ]
