# Generated by Django 4.1.1 on 2022-10-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fkip', '0003_alter_dosen_photo_alter_mahasiswa_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='alamat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='photo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='photo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='prodi',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='alamat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
